### ISSUE TITLE
Facet selection on home page without a search term

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-app#26]
As a user, I'd like to select all docs with facets available on the results page but without searching a specific term. 

For example, I'd like to see all mailing list posts by Greg Maxwell or all docs by Pieter Wuille from stack exchange. 

Maybe we can do this with a collection of the pills for the domains and authors. Let's leave tags out.

**Comment by Emmanuel-Develops** [comment]
For facets to have any data there needs to be a request. In the App.jsx, there's a config `alwaysSearchOnInitialLoad: false` changing that to `true` provides all the possible data from search and populates the facets. The question is should we show those results on initial page load? 

The results are in date descending order so it's visually looks like latest articles.

This issue is also liked with #22 

Also some clarity on "Maybe we can do this with a collection of the pills"

**Comment by adamjonas** [comment]
I was suggesting maybe that we seed the front page with some authors and domains to search. For example, I'd like to see all mailing list posts from Bob Smith. Based on what you described there is probably some UI to hit search once you've selected the facets you want to see but this seems murky for me so let's deprioritize for now.

**Comment by Emmanuel-Develops** [comment]
I have a UI in mind that can potentially solve this. I'll implement it then we can test it.

**Comment by adamjonas** [comment]
closed by #62
